<?php
include 'header.php';

// 1. Get the PO ID from the URL safely
$po_id = isset($_GET['id']) ? intval($_GET['id']) : 0;

if ($po_id == 0) {
    echo "<div class='alert alert-danger'>Invalid Purchase Order ID.</div>";
    include 'footer.php';
    exit();
}

// 2. Fetch the Main PO and Vendor Details
$poQuery = "
    SELECT p.*, v.company_name, v.address, v.city, v.state, v.gst_number, v.contact_person, v.email, v.phone,
           u.first_name, u.last_name 
    FROM purchase_orders p
    JOIN vendors v ON p.vendor_id = v.vendor_id
    JOIN users u ON p.generated_by = u.user_id
    WHERE p.po_id = $po_id
";
$poResult = mysqli_query($conn, $poQuery);

if (mysqli_num_rows($poResult) == 0) {
    echo "<div class='alert alert-warning'>Purchase Order not found.</div>";
    include 'footer.php';
    exit();
}

$po = mysqli_fetch_assoc($poResult);

// 3. Fetch the Items for this PO
$itemsQuery = "SELECT * FROM purchase_order_items WHERE po_id = $po_id";
$itemsResult = mysqli_query($conn, $itemsQuery);

// Determine Status Badge Color
$badgeClass = 'bg-secondary';
if (in_array($po['status'], ['Generated', 'Sent'])) $badgeClass = 'bg-warning text-dark';
if (in_array($po['status'], ['Accepted', 'Completed'])) $badgeClass = 'bg-success';
if ($po['status'] == 'Cancelled') $badgeClass = 'bg-danger';
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <a href="dashboard.php" class="btn btn-light border shadow-sm me-2"><i class="bi bi-arrow-left"></i> Back</a>
        <h2 class="d-inline-block align-middle mb-0">Purchase Order Details</h2>
    </div>
    <div>
        <button onclick="window.print()" class="btn btn-dark shadow-sm"><i class="bi bi-printer"></i> Print PO</button>
    </div>
</div>

<div class="card shadow-sm border-0" id="print-area">
    <div class="card-body p-5">
        
        <div class="row border-bottom pb-4 mb-4">
            <div class="col-sm-6">
                <h3 class="fw-bold text-primary mb-0"><i class="bi bi-buildings"></i> VendorBridge</h3>
                <p class="text-muted small">Procurement Management System</p>
            </div>
            <div class="col-sm-6 text-end">
                <h1 class="text-uppercase text-muted" style="letter-spacing: 2px;">Purchase Order</h1>
                <h4 class="fw-bold text-dark"><?php echo htmlspecialchars($po['po_number']); ?></h4>
                <span class="badge <?php echo $badgeClass; ?> fs-6 mt-1"><?php echo htmlspecialchars($po['status']); ?></span>
            </div>
        </div>

        <div class="row mb-5">
            <div class="col-sm-6">
                <h6 class="text-muted text-uppercase fw-bold mb-3">Vendor Details:</h6>
                <h5 class="fw-bold mb-1"><?php echo htmlspecialchars($po['company_name']); ?></h5>
                <div class="text-muted">
                    <p class="mb-0"><i class="bi bi-person"></i> <?php echo htmlspecialchars($po['contact_person']); ?></p>
                    <p class="mb-0"><i class="bi bi-envelope"></i> <?php echo htmlspecialchars($po['email']); ?> | <i class="bi bi-telephone"></i> <?php echo htmlspecialchars($po['phone']); ?></p>
                    <p class="mb-0 mt-1"><strong>GSTIN:</strong> <?php echo htmlspecialchars($po['gst_number'] ?? 'N/A'); ?></p>
                    <p class="mb-0"><?php echo htmlspecialchars($po['address'] . ', ' . $po['city'] . ', ' . $po['state']); ?></p>
                </div>
            </div>
            <div class="col-sm-6 text-end">
                <h6 class="text-muted text-uppercase fw-bold mb-3">Order Details:</h6>
                <table class="table table-sm table-borderless text-end mb-0 float-end" style="width: 250px;">
                    <tr><td class="text-muted">PO Date:</td><td class="fw-bold"><?php echo date('d M Y', strtotime($po['po_date'])); ?></td></tr>
                    <tr><td class="text-muted">Generated By:</td><td class="fw-bold"><?php echo htmlspecialchars($po['first_name'] . ' ' . $po['last_name']); ?></td></tr>
                    <tr><td class="text-muted">Ref Quote ID:</td><td class="fw-bold">#<?php echo htmlspecialchars($po['quotation_id']); ?></td></tr>
                </table>
            </div>
        </div>

        <table class="table table-bordered mb-5">
            <thead class="table-light">
                <tr>
                    <th width="5%">#</th>
                    <th width="50%">Product / Service Description</th>
                    <th width="15%" class="text-center">Quantity</th>
                    <th width="15%" class="text-end">Unit Price (₹)</th>
                    <th width="15%" class="text-end">Total (₹)</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $count = 1;
                if (mysqli_num_rows($itemsResult) > 0) {
                    while ($item = mysqli_fetch_assoc($itemsResult)) { 
                ?>
                    <tr>
                        <td><?php echo $count++; ?></td>
                        <td><?php echo htmlspecialchars($item['product_name']); ?></td>
                        <td class="text-center"><?php echo number_format($item['quantity'], 2); ?></td>
                        <td class="text-end"><?php echo number_format($item['unit_price'], 2); ?></td>
                        <td class="text-end fw-bold"><?php echo number_format($item['total_price'], 2); ?></td>
                    </tr>
                <?php 
                    } 
                } else { 
                ?>
                    <tr>
                        <td colspan="5" class="text-center py-4 text-muted">
                            <em>Line items are detailed in the attached quotation #<?php echo $po['quotation_id']; ?>.</em>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

        <div class="row">
            <div class="col-sm-7">
                <p class="text-muted small"><strong>Terms & Conditions:</strong><br>
                1. Delivery must be completed within the agreed timeframe.<br>
                2. Quote this PO number on all invoices and delivery challans.<br>
                3. Payment will be processed as per standard Net 20 Day terms.</p>
            </div>
            <div class="col-sm-5">
                <table class="table table-sm table-borderless text-end fs-5">
                    <tr class="border-top border-dark border-2">
                        <td class="text-muted fw-bold">Grand Total:</td>
                        <td class="fw-bold text-success">₹<?php echo number_format($po['total_amount'], 2); ?></td>
                    </tr>
                </table>
            </div>
        </div>

    </div>
</div>

<style>
/* This hides the sidebar and topbar when the user clicks 'Print' */
@media print {
    body * { visibility: hidden; }
    #print-area, #print-area * { visibility: visible; }
    #print-area { position: absolute; left: 0; top: 0; width: 100%; border: none; box-shadow: none; }
    .btn, nav, .sidebar { display: none !important; }
}
</style>

<?php include 'footer.php'; ?>