<?php
include 'header.php';

// Fetch data specifically for THIS PO
$activeRfqsQuery = mysqli_query($conn, "SELECT COUNT(*) as count FROM rfqs WHERE status = 'Open' AND created_by = $user_id");
$myActiveRfqs = mysqli_fetch_assoc($activeRfqsQuery)['count'] ?? 0;

$pendingQuotesQuery = mysqli_query($conn, "
    SELECT COUNT(*) as count FROM quotations q 
    JOIN rfqs r ON q.rfq_id = r.rfq_id 
    WHERE q.status = 'Submitted' AND r.created_by = $user_id
");
$newBids = mysqli_fetch_assoc($pendingQuotesQuery)['count'] ?? 0;

$myPosQuery = mysqli_query($conn, "SELECT COUNT(*) as count FROM purchase_orders WHERE generated_by = $user_id");
$myTotalPos = mysqli_fetch_assoc($myPosQuery)['count'] ?? 0;

// Fetch their recent RFQs
$recentRfqs = mysqli_query($conn, "SELECT * FROM rfqs WHERE created_by = $user_id ORDER BY created_at DESC LIMIT 5");
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h2>My Sourcing Dashboard</h2>
    <a href="create_rfq.php" class="btn btn-primary shadow-sm"><i class="bi bi-plus-circle"></i> Create New RFQ</a>
</div>

<div class="row mb-4 g-3">
    <div class="col-md-4">
        <div class="stat-card border-bottom border-primary border-3">
            <h3><?php echo number_format($myActiveRfqs); ?></h3>
            <p>My Active RFQs</p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="stat-card border-bottom border-warning border-3">
            <h3><?php echo number_format($newBids); ?></h3>
            <p>New Vendor Bids Received</p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="stat-card border-bottom border-success border-3">
            <h3><?php echo number_format($myTotalPos); ?></h3>
            <p>POs Generated By Me</p>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-white border-bottom py-3">
        <h5 class="mb-0 text-primary"><i class="bi bi-clock-history"></i> My Recent RFQs</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>RFQ Number</th>
                        <th>Title</th>
                        <th>Deadline</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (mysqli_num_rows($recentRfqs) > 0) { 
                        while ($row = mysqli_fetch_assoc($recentRfqs)) { 
                            $badge = 'bg-secondary';
                            if ($row['status'] == 'Open') $badge = 'bg-primary';
                            if ($row['status'] == 'Draft') $badge = 'bg-warning text-dark';
                            if ($row['status'] == 'Closed') $badge = 'bg-dark';
                    ?>
                    <tr>
                        <td class="fw-bold"><i class="bi bi-tag text-muted"></i> <?php echo htmlspecialchars($row['rfq_number']); ?></td>
                        <td><?php echo htmlspecialchars($row['title']); ?></td>
                        <td class="<?php echo (strtotime($row['deadline']) < time() && $row['status'] == 'Open') ? 'text-danger fw-bold' : ''; ?>">
                            <?php echo date('d M Y, h:i A', strtotime($row['deadline'])); ?>
                        </td>
                        <td><span class="badge <?php echo $badge; ?>"><?php echo htmlspecialchars($row['status']); ?></span></td>
                        <td>
                            <?php if(in_array($row['status'], ['Open', 'Draft'])): ?>
                            <a href="edit_rfq.php?id=<?php echo $row['rfq_id']; ?>" class="btn btn-sm btn-outline-primary border">
                                <i class="bi bi-gear"></i> Manage
                            </a>
                            <?php else: ?>
                                <a href="rfqs.php" class="btn btn-sm btn-light border text-muted">
                                    <i class="bi bi-lock"></i> Locked
                                </a>
                            <?php endif; ?>                        
                        </td>
                    </tr>
                    <?php } } else { ?>
                        <tr><td colspan="5" class="text-center py-4 text-muted">You haven't created any RFQs yet.</td></tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include 'footer.php'; ?>